baseURL = "https://www.evolvingcomplexity.io/"
languageCode = "en-gb"
title = "Evolving Complexity"
theme = "noteworthy"

paginate = 4
summaryLength = 10

[params]
    description = "Something in here about the blog..."

[[menu.main]]
    identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1

[[menu.main]]
    identifier = "talks"
	name = "Talks"
	url = "/talks/"
	weight = 2

[[menu.main]]
    identifier = "contact"
	name = "Contact"
	url = "/contact/"
	weight = 3