baseURL = "https://www.evolvingcomplexity.io/"
languageCode = "en-gb"
title = "Evolving Complexity"
theme = "noteworthy"

googleAnalytics = ""

paginate = 5
summaryLength = 10

[taxonomies]
  tag = "tags"

[params]
    description = "Hey 👋 I'm Ryan Kerry - I brain dump and blog here about technical leadership, engineering management and technology."

	twitter = "https://twitter.com/RyanKerry1"
	linkedin = "https://www.linkedin.com/in/ryank90"
	github = "https://github.com/Ryank90"
	stackoverflow = "https://stackoverflow.com/users/1556123/ryank"

[[menu.main]]
    identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1

[[menu.main]]
    identifier = "talks"
	name = "Talks"
	url = "/talks/"
	weight = 2

[[menu.main]]
    identifier = "contact"
	name = "Contact"
	url = "/contact/"
	weight = 3

